{
    "position": "string",
    "header": "string",
    "module": "string",
    "config": "object",

    "displayType": "string",
    "displaySeconds": "boolean",
    "showPeriod": "boolean",
    "showPeriodUpper": "boolean",
    "clockBold": "boolean",
    "showDate": "boolean",
    "showWeek": "boolean",
    "dateFormat": "string",
    "lunarShow": "boolean",
    "timeFormat": "number",
    "analogSize": "string",
    "analogFace": "string",
    "analogPlacement": "string",
    "analogShowDate": "string",
    "secondsColor": "string",
    "showSunTimes": "boolean",
    "showMoonTimes": "boolean",
    "lat": "number",
    "lon": "number",

    "maximumEntries": "number",
    "maximumNumberOfDays": "number",
    "showLocation": "boolean",
    "maxTitleLength": "number",
    "wrapEvents": "boolean",
    "maxTitleLines": "number",
    "fetchInterval": "number",
    "animationSpeed": "number",
    "displayButton": "boolean",
    "displayEndTime": "boolean",
    "displayLunarDate": "boolean",
    "displayPersonalEvents": "boolean",
    "dateEndFormat": "string",
    "defaultColor": "string",
    "lunarColor": "string",
    "colored": "boolean",
    "displayLunarEvents": "boolean",
    "calendars": "object",
    "url": "string",
    "color": "string",
    "name": "string",
    "personalDateEvent": "object",
    "day": "number",
    "month": "number",
    "title": "string",

    "streamVideo": "boolean",
    "displayRate": "boolean",
    "updateInterval": "number",
    "userName": "object",
    "ThayDuy":"string",
    "ThayDuong":"string",
    "Quan":"string",
    "Khanh":"string",
    "Bao":"string",
    "BuiPhungHuuDuc":"string",
    "ChauMinhDuc":"string",
    "Dat":"string",
    "Dung":"string",
    "Duy":"string",
    "Giang":"string",
    "Huy":"string",
    "LAnh":"string",
    "Nhu":"string",
    "Phong":"string",
    "Quoc":"string",
    "Tin":"string",
    "Van":"string",

    "initLedMMM": "string",
    "allowGA": "boolean",
    "allowGesture": "boolean",

    "flakeCount": "number",
    "theme": "string",
    "sizeFactor": "number",
    "downwards": "boolean",

    "effect": "string",
    "alert_effect": "string",
    "display_time": "number",
    "welcome_message": "boolean",

    "interval": "number",
    "colorDark": "string",
    "colorLight": "string",
    "imageSize": "number",

    "showSourceTitle": "boolean",
    "showPublishDate": "boolean",
    "showDescription": "boolean",
    "wrapTitle": "boolean",
    "wrapDescription": "boolean",
    "truncDescription": "boolean",
    "lengthDescription": "number",
    "hideLoading": "boolean",
    "reloadInterval": "number",
    "maxNewsItems": "number",
    "ignoreOldItems": "boolean",
    "ignoreOlderThan": "number",
    "logFeedWarnings": "boolean",
    "feeds": "object",

    "location": "string",
    "locationID": "string",  
    "units": "string",
    "showWindDirection": "boolean",
    "showWindDirectionAsArrow": "boolean",
    "useBeaufort": "boolean",
    "appendLocationNameToHeader": "boolean",
    "useKMPHwind": "boolean",
    "decimalSymbol": "string",
    "showHumidity": "boolean",
    "degreeLabel": "boolean",
    "showIndoorTemperature": "boolean",
    "showIndoorHumidity": "boolean",
    "showFeelsLike": "boolean",
    "initialLoadDelay": "number",
    "retryDelay": "number",
    "roundTemp": "boolean",

    "maxNumberOfDays": "number",
    "showRainAmount": "boolean",
    "fade": "boolean",
    "fadePoint": "number",
    "scale": "boolean",
    "calendarClass": "string",
    "tableClass": "string",

    "micConfig": "object", 
    "recorder": "string",
    "device": "string",
    "snowboy": "object", 
    "usePMDL": "boolean",
    "audioGain": "number",
    "Frontend": "boolean",
    "Model": "string",
    "Sensitivity": "number",
    "A2DServer": "object", 
    "useA2D": "boolean",
    "stopCommand": "string",
    "useYouTube": "boolean",
    "youtubeCommand": "string",
    "displayResponse": "boolean",
    "recipes":"object",
    "myCustomRecipe.js":"string",

    "modules":"object",
    "fixed": "object",
    "MMM-VietnamCalendar": "string",
    "weatherforecast": "string",
    "MMM-News-QR": "string",
    "newsfeed": "string",
    "MMM-Tools": "string",
    "MMM-FaceNet": "string",
    "currentweather": "string",
    "MMM-News-QR": "string",
    "newsfeed": "string",
    "MMM-GoogleDriveSlideShow": "string",
    "MMM-Snow": "string",
    "MMM-GroveGestures": "string",
    "clock": "string",
    "MMM-Assistant2Display": "string",
    "MMM-GoogleAssistant": "string",
    "MMM-pages": "string",
    "MMM-page-indicator": "string",
    "animationTime": "number",

    "refresh_interval_ms": "number",
    "databaseSave": "boolean",

    "recognitionTimeout": "number",
    "visible": "boolean", 

    "rootFolderId": "string",
    "maxFolders": "number",
    "maxResults": "number",
    "refreshDriveDelayInSeconds": "number",
    "refreshSlideShowIntervalInSeconds": "number",
    "maxWidth": "string",
    "maxHeight": "string",
    "theme": "string",
    "opacity": "number",
    "debug": "boolean",

    "pages": "number"

}
