{
    "position": "string",
    "header": "string",
    "module": "string",
    "config": "object",
    "maximumEntries": "number",
    "maximumNumberOfDays": "number",
    "showLocation": "boolean",
    "maxTitleLength": "number",
    "wrapEvents": "boolean",
    "maxTitleLines": "number",
    "fetchInterval": "number",
    "animationSpeed": "number",
    "displayButton": "boolean",
    "displayEndTime": "boolean",
    "displayLunarDate": "boolean",
    "displayPersonalEvents": "boolean",
    "dateEndFormat": "string",
    "defaultColor": "string",
    "lunarColor": "string",
    "colored": "boolean",
    "tableClass": "string",
    "displayLunarEvents": "boolean",
    "userName": "object",
    "ThayDuy":"string",
    "ThayDuong":"string",
    "Quan":"string",
    "Khanh":"string",
    "Bao":"string",
    "BuiPhungHuuDuc":"string",
    "ChauMinhDuc":"string",
    "Dat":"string",
    "Dung":"string",
    "Duy":"string",
    "Giang":"string",
    "Huy":"string",
    "LAnh":"string",
    "Nhu":"string",
    "Phong":"string",
    "Quoc":"string",
    "Tin":"string",
    "Van":"string",
    "calendars": "object",
    "url": "string",
    "color": "string",
    "name": "string",
    "personalDateEvent": "object",
    "day": "number",
    "month": "number",
    "title": "string"
}
